"""db init

Revision ID: 7144dc983e42
Revises: 
Create Date: 2021-03-23 20:47:57.750420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7144dc983e42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jscode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jscode', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jscode_description'), 'jscode', ['description'], unique=True)
    op.create_index(op.f('ix_jscode_jscode'), 'jscode', ['jscode'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jscode_jscode'), table_name='jscode')
    op.drop_index(op.f('ix_jscode_description'), table_name='jscode')
    op.drop_table('jscode')
    # ### end Alembic commands ###
